
/run/initialize

#visualizacion
/vis/open OGLSQt 600x600-0+0
/vis/drawVolume

#ajustes de cámara y estilo
/vis/viewer/set/viewpointThetaPhi 45 45
/vis/viewer/set/style wireframe
/vis/viewer/set/autoRefresh true

#elementos visuales
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/scene/add/axes 0 0 0 10 cm

#refrescar en cada evento para evitar lag
/vis/scene/endOfEventAction refresh

#1 evento para verificar
/run/beamOn 1